[workspace]
members = [
    "packages/derive_builder",
    "packages/flatten_iterator",
    "packages/kilo",
    "packages/minigrep",
    "packages/organon",
    "packages/sandbox",
    "packages/webserver",
]
exclude = ["packages/rustos"]

[workspace.dependencies]
color-eyre = "0.6.2"
proc-macro2 = "1.0.47"
quote = "1.0.21"
syn = "1.0.103"
trybuild = "1.0.71"
