[package]
name = "synex"
version = "0.0.0"
edition = "2021"
publish = false

[features]
testsuite = []

[dependencies]
# Procedural macros
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
